# apiVersion: backstage.io/v1alpha1
# kind: Group
# metadata:
#   name: team-a
# spec:
#   type: team
#   children: []
# ---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: christseng89
spec:
  profile:
    displayName: Christ Tseng
    email: samfire5200@gmail.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Leo&backgroundColor=transparent
  memberOf: [development]
