apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MasterBackstageIdp
  annotations:
    github.com/project-slug: christseng89/MasterBackstageIdp
spec:
  type: service
  owner: development
  lifecycle: experimental

