redis-ha:
  enabled: false

controller:
  replicas: 1
  extraArgs:
    - --repo-server-timeout-seconds=300

repoServer:
  replicas: 1
  extraArgs:
    - --request-timeout=300s

applicationSet:
  replicas: 1

global:
  domain: argocd.test.com

certificate:
  enabled: false

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    tls: false

configs:
  cm:
    url: http://argocd.test.com:9080
  params:
    server.insecure: "true"
  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, admin, role:admin
    policy.matchMode: glob
    scopes: "[groups]"
