site_name: "python-app"
site_description: "Main documentation for the python-app"
repo_url: https://github.com/christseng89/MasterBackstageIdp
edit_uri: edit/main/python-app/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Home: index.md
  - Test: test.md
