apiVersion: v1
kind: Namespace
metadata:
  name: python-app
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: self-hosted-runner
  namespace: python-app
spec:
  replicas: 1
  template:
    spec:
      repository: christseng89/MasterBackstageIdp
      dockerEnabled: true
