apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arc-runner-reader-python-app
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arc-runner-reader-python-app
subjects:
  - kind: ServiceAccount
    name: default
    namespace: python-app
roleRef:
  kind: ClusterRole
  name: arc-runner-reader-python-app
  apiGroup: rbac.authorization.k8s.io
